# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00862ade666e0693868954d39f27a1fc29b8a2247d858652e329c47d438a52940a2ebd74d5b93380e73b7b957ec809f6ae6f079cbcea4e351246c9ac1b7d7dfd

test:
  secret_key_base: bb15224a32b720238464bea1d53e8e1cb6b3f28e5209b57801edab4a785cfec5b191cd91fe7e2b9a7a9bda8bb6a87714eca605ae8ba46d5c373038167753ac75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
